### ISSUE TITLE
upgrade.log error: undefined symbol: gdk_pixbuf_gettext

### ISSUE THREAD

**Issue by drehak** [upgrades-migrations/preupgrade-assistant-modules#111]
Following errors were found in *upgrade.log*:
```
upgrade[5124]: [469/558] (64%) installing gdk-pixbuf2-2.36.12-3.el7...
upgrade[5124]: g_module_open() failed for /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pcx.so: /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pcx.so: undefined symbol: gdk_pixbuf_gettext
upgrade[5124]: g_module_open() failed for /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ras.so: /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ras.so: undefined symbol: gdk_pixbuf_gettext
upgrade[5124]: g_module_open() failed for /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-wbmp.so: /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-wbmp.so: undefined symbol: gdk_pixbuf_gettext
```
Likely caused by **gdk-pixbuf2** install scriptlet, but I'm not entirely sure about its low severity (linker errors could be important), hence reported.

Reproduced with:
 *  *preupgrade-assistant-el6toel7-0.7.7-1.el6.noarch*
 *  *redhat-upgrade-tool-0.8.0-4.el6.noarch*

**Comment by pirat89** [comment]
Nothing we can/will do here.

**Comment by AloisMahdal** [comment]
RHEL-6 has reached EOL last year, and we're not planning any further releases.

After discussion with @shaded-enmity we've decided to close any outstanding issues that aren't causing known functional issues.

See OAMG-5050 internal ticket for more details.

**Comment by pirat89** [comment]
Looking into the list of issues, I think it doesn't make sense to close them. we will just archive the repository and that's it.
