### ISSUE TITLE
upgrade.log error: pax link exists

### ISSUE THREAD

**Issue by drehak** [upgrades-migrations/preupgrade-assistant-modules#115]
Following errors were found in *upgrade.log* (including context):
```
upgrade[5116]: [182/658] (25%) installing spax-1.5.2-13.el7...
upgrade[5116]: failed to link /usr/bin/pax -> /etc/alternatives/pax: /usr/bin/pax exists and it is not a symlink
upgrade[5116]: failed to link /usr/share/man/man1/pax.1.gz -> /etc/alternatives/pax-man: /usr/share/man/man1/pax.1.gz exists and it is not a symlink
[ ... ]
upgrade[5116]: [606/658] (70%) installing pax-3.4-19.el7...
upgrade[5116]: failed to link /usr/share/man/man1/pax.1.gz -> /etc/alternatives/pax-man: /usr/share/man/man1/pax.1.gz exists and it is not a symlink
```
The culprit is surely the post/preun scriptlet (http://pkgs.devel.redhat.com/cgit/rpms/pax/tree/pax.spec?h=rhel-7.6). I'm just putting it here so that we have some data about it (and that there's an associated issue in the cleanser), since we haven't had link errors so far.

Reproduced with:
 *  *preupgrade-assistant-el6toel7-0.7.7-1.el6.noarch*
 *  *redhat-upgrade-tool-0.8.0-4.el6.noarch*

**Comment by drehak** [comment]
Another similar one:
```
upgrade[5559]: [421/560] (58%) installing mariadb-server-5.5.60-1.el7_5...
upgrade[5559]: failed to link /usr/bin/mysqlbug -> /etc/alternatives/mysqlbug: /usr/bin/mysqlbug exists and it is not a symlink
```
Is it noteworthy or should I just cleanse all link fails?

**Comment by AloisMahdal** [comment]
Pretty much the same thing:

    [  195.076197] upgrade[3207]: [3/452] (76%) cleaning sendmail-8.14.4-9.el6_8.1... 
    [  195.085629] upgrade[3207]: failed to link /usr/share/man/man8/rmail.8.gz -> /etc/alternatives/mta-rmailman: /usr/share/man/man8/rmail.8.gz exists and it is not a symlink

**Comment by AloisMahdal** [comment]
RHEL-6 has reached EOL last year, and we're not planning any further releases.

After discussion with @shaded-enmity we've decided to close any outstanding issues that aren't causing known functional issues.

See OAMG-5050 internal ticket for more details.
