### ISSUE TITLE
Do not remove solution.txt in check scripts

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant-modules#21]
The Preupgrade Assistant expects _solution.txt_ in each module's directory, it's considered as required now. Some of the modules, however, remove the _solution.txt_ within the _check_ script. I know about `drivers/ObsoletedStorageDrivers/` and `drivers/ObsoletedNetworkDrivers/` but others might be doing it too.

**Comment by pirat89** [comment]
These modules should be checked:
```bash
$ grep -iEr "rm\s+[-rf]*\s*(solution|\$SOLUTION)" | cut -d ":" -f 1 | sort | grep -v "matches" | uniq | grep -o "^.*/"
RHEL6_7/desktop/GNOME/
RHEL6_7/desktop/KDE/
RHEL6_7/drivers/ObsoletedGraphicDrivers/
RHEL6_7/drivers/ObsoletedInputDrivers/
RHEL6_7/drivers/ObsoletedNetworkDrivers/
RHEL6_7/drivers/ObsoletedStorageDrivers/
RHEL6_7/networking/nfsv2/
RHEL6_7/others/rsyslog/
RHEL6_7/packages/GenericUtilities/
RHEL6_7/packages/InterVariants/
RHEL6_7/packages/notbase-channel/
RHEL6_7/packages/ObsoletedPackages/
RHEL6_7/packages/RemovedPackages/
RHEL6_7/packages/ReplacedPackages/
RHEL6_7/selinux/CustomPolicy/
RHEL6_7/system/FHS/Run/
RHEL6_7/system/polkit/
RHEL6_7/system/requirements/
RHEL6_7/system/SonameBump/
RHEL6_7/system/SonameRemoval/
RHEL6_7/system/SystemVersion/
RHEL6_7/usrmgmt/DangerousRanges/
RHEL6_7/usrmgmt/ReservedIDs/
```

**Comment by AloisMahdal** [comment]
Why not just make it optional?  IMO the requirement does not make much sense anyway; there's no reason to have a file that is empty.

**Comment by bocekm** [comment]
Ok, I will make the solution.txt non-required in the Preupgrade Assistant. Now it's up to you, @pirat89, if you want to update the modules or not. If not, close the issue.

**Comment by pirat89** [comment]
Ok. In that case I will close it as it doesn't make sense to create the files when they will not be required.
