### ISSUE TITLE
During the upgrade from RHEL-6.9 to RHEL-7.4 no grub2 package is installed

### ISSUE THREAD

**Issue by msibacalm** [upgrades-migrations/preupgrade-assistant-modules#23]
https://bugzilla.redhat.com/show_bug.cgi?id=1497731

Could you please take a look into that and let me know when you will prepare update to provide script which installs grub2 during upgrade ?

Thanks

**Comment by pirat89** [comment]
Fix would be applied during tomorrow when it is tested. See branch grub.
