### ISSUE TITLE
Support for assessment format version: stage 1 (p-a-m)

### ISSUE THREAD

**Issue by AloisMahdal** [upgrades-migrations/preupgrade-assistant-modules#31]
This is part of a greater change that needs to be done in all three codebases in 3 stages:

  * [ ] 1. **modules** (this ticket),
  * [ ] 2. preupgrade-assistant ([#335][s2]),
  * [ ] 3. redhat-upgrade-tool ([#31][s3]).

  [s2]: https://github.com/upgrades-migrations/preupgrade-assistant/issues/335
  [s3]: https://github.com/upgrades-migrations/redhat-upgrade-tool/issues/31

Below is the complete description:

---

Assessment, as a data object does not currently have any concept of versioning.  Any tools that further work with it (redhat-upgrade-tool, preupg-kickstart-creator, preupg UI...) simply have to assume that they "understand" the data.

The solution is to introduce assessment format version.   The flow is:

 *  Module set declares its abability to produce assessment in version $V.  This can be done
    by means of key/value pair in properties.ini

        assessment_format_version = 0.1

 *  Assisstant launches modules and passes this information as part of assessment
    somewhere under (/root/preupgrade as well as in tarball).

 *  *redhat-upgrade-tool* hardcodes range of versions (actually just one particular version)
    it's able to "understand" and compares this against assessment version.  If the versions
    match, it can continue.  If the versions don't match or assessment version cannot be
    determined, it advises user to install respective module set and re-run assessment.

**Comment by AloisMahdal** [comment]
My recommendation is that actual versioning should conform to [SemVer][1], with the exception that as data format, using `x.y` is enough ("patches" don't make a lot of sense for data formats).

As starting point, I would suggest the version be `0.0` (see my [0to1 convention proposal][2]) or `0.1`.

  [1]: http://semver.org/
  [2]: https://github.com/mojombo/semver/issues/363

**Comment by pirat89** [comment]
Closing the request as after discussion this does not seem relevant. The version of format of assessment will by specified by preupgrade-assistant. Not by modules.
