### ISSUE TITLE
RestoreConfig: post-upgrade fails

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant-modules#39]
The post-upgrade script uses as input for the semanage commane lines from the file `semanage_export`. But the error occurs during post-upgrade phase when the file contains line as below:

```
fcontext -a -f 'directory' -t root_t '/opt/rh/xyz'
```

The error:
```
semanage fcontext: error: argument -f/--ftype: invalid choice: "'directory'" (choose from 'a', 'f', 'd', 'c', 'b', 's', 'l', 'p')
usage: semanage fcontext [-h] [-n] [-N] [-S STORE] [ --add ( -t TYPE -f FTYPE -r RANGE -s SEUSER | -e EQUAL ) FILE_SPEC ) | --delete ( -t TYPE -f FTYPE | -e EQUAL ) FILE_SPEC ) | --deleteall  | --extract  | --list -C | --modify ( -t TYPE -f FTYPE -r RANGE -s SEUSER | -e EQUAL ) FILE_SPEC ) ]
Could not import 'fcontext -a -f 'directory' -t root_t '/opt/rh/xyz''
```

Similar errors can be seen for other lines, like:
```
Could not import 'boolean -1 xen_use_nfs'
```

**Comment by AloisMahdal** [comment]
At least 2 downstream upgrade tests keep failing because of this.

**Comment by pirat89** [comment]
I will keep in mind for next milestone

**Comment by jmazanek** [comment]
Created PR with a fix : https://github.com/upgrades-migrations/preupgrade-assistant-modules/pull/78

**Comment by AloisMahdal** [comment]
I've looked a bit into it and IIUC, I don't think this can be done using sed; you'll need to use Bash tokenization.

Let me suggest different approach:

 1. Write a function that translates all its positional args into the new syntax and calls the new utility.

        foo() {
                local args=()
                while true; do case $1 in in
                    -a) args+=("--all"); shift ;;
                    ..) args+=("--all"); shift ;;
                   unknown)  panic ;;
                    "") break ;;
                esac done
                semanage "${args[@]}"
        }

 2. Prefix every line in semanage_export with name of this function.

        semanage_new=$(sed 's/^/foo /' semanage_export)

 3. Just eval semanage_export

        bash -n <<<"$semanage_new" || panic
        eval "$semanage_new"

This way, you will be able to re-use the Bash tokenization.
