### ISSUE TITLE
mysql/configuration_changes: configs stored outside of {dirty,clean}conf

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant-modules#61]
The configuration files are stored outside of dirtyconf and cleanconf directories and do not see they are really used in the end (maybe I overlooked something). Review this module better. And probably move configs to the correct place.

**Comment by jmazanek** [comment]
Created PR# fixing the problem (copies files to dirtyconf) - https://github.com/upgrades-migrations/preupgrade-assistant-modules/pull/99
