### ISSUE TITLE
Create a module to help with upgrade from SMBv1 to SMBv2

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant-modules#7]
Since RHEL 7.2, there's an added support for SMBv2. Microsoft is discontinuing SMBv1 (https://blogs.technet.microsoft.com/filecab/2016/09/16/stop-using-smb1/), so for people on RHEL 6 using SMBv1, there's an option to upgrade to RHEL 7.2+ and start using SMBv2.

**Comment by jmazanek** [comment]
Looking at it. Doing research, what can be done now

**Comment by jmazanek** [comment]
Module created - please see https://github.com/upgrades-migrations/preupgrade-assistant-modules/pull/11

**Comment by jmazanek** [comment]
Related PR had been merged into master branch. Closing issue
