### ISSUE TITLE
system/initscripts/ifcfg: modify module to keep best practices

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant-modules#72]
Because of time, we planned these changes for next milestone:

- [x] replace extreme risks by high risks and create/modify a pre-upgrade script
  to inhibit upgrade in case user haven't fixed that before run of r-u-t
- [x] not sure about the high risk msg when multiple network devices using ethX
  naming are detected - maybe should say in summary what is expected from user
  so user will know that it is expected to check the solution whether want to
  use netX naming or something else.
- [x] use PA API variables inside the preupg_network.sh script

Related: #68

**Comment by jmazanek** [comment]
@pirat89 regarding the second point - I have decided to leave the log risk message as it is and add the explanation to the solution. I think it is better as the log messages should stay brief
