### ISSUE TITLE
improve the samba module

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant-modules#79]
According to offline discussion, we will improve the samba module in this way:
- [x] log medium risk with info that current configuration might be broken on RHEL 7 system
- [x] with that print relevant solution text like: *Check the output of 'testparm' to see if there are any options in smb.conf that are no longer supported with the samba version shipped as part of Red Hat Enterprise Linux 7*
- [x] post-upgrade script will run `testparm` and report error message that configuration is broken and user has to modify the configuration file manually

**Comment by jmazanek** [comment]
Resolved in PR# https://github.com/upgrades-migrations/preupgrade-assistant-modules/pull/98
