### ISSUE TITLE
system/initscripts/ifcfg: incorrect regexp?

### ISSUE THREAD

**Issue by pirat89** [upgrades-migrations/preupgrade-assistant-modules#84]
The line below contains extended regular expression which is parsed as basic reular expression. Unless the `+` char should be evaluated as the `+` char, use the `-E` option or fix the regex.

https://github.com/upgrades-migrations/preupgrade-assistant-modules/blob/03d3166fe234c86528bcabca3f52b74388dad668/RHEL6_7/system/initscripts/ifcfg/preupg_network.sh#L36

**Comment by jmazanek** [comment]
https://github.com/upgrades-migrations/preupgrade-assistant-modules/pull/86
fixes the issue
